apiVersion: v1 # version of the Kubernetes API 
kind: Service # type of Kubernetes object to create
metadata:
  name: nginx-service
spec:
  type: NodePort # Services expose the Service on a static port on each Node in the cluster
  selector: # how the Service finds the Pods it should route traffic to
    app: nginx # This selector tells the nginx-service to direct traffic to any Pods that have the label app: nginx
  ports:
  - port: 80 # This is the port on the Service 
    targetPort: 80 # This is the port on the container
# Kubernetes reserves the port range 30000-32767 for NodePort Services. You must choose a port within this range
    nodePort: 30800  # NodePort must be in the range 30000-3276 
